cache:
  directories:
    - $HOME/.m2
language: java
jdk: openjdk11
install: true
script: 
  - ./build.sh

deploy:
 provider: gae
 keyfile: /home/eduardo/Downloads/erp-test-202020-fb7a70a703a8.json
 project: "erp-test-202020"
 on:
   branch: main
